export const PricesList = [
	{
		id: 1,
        pricipal: false,
		title: 'Iniciante',
		subtitle: '',
        description: 'Uma ajudinha sempre cai bem',
        value: "50",
        interval: "Hora",
        item1: "Combine o melhor horário",
        item2: "Escolha o seu professor",
        item3: "Duração mínima de 2h*",
        link: "https://api.whatsapp.com/send?phone=5586995185757&text=Ol%C3%A1!%20Gostaria%20de%20contratar%20o%20Plano%20Iniciante.%0APode%20me%20ajudar%3F",
    },
	{
		id: 2,
        pricipal: true,
		title: 'Mensal Simples',
		subtitle: 'Melhor Opção',
        description: 'Para uma orientação mais de perto',
        value: "380",
        interval: "Mês",
        item1: "Total de 4 aulas (2h) no mês",
        item2: "Dúvidas por WhatsApp",
        item3: "Economia de 5%",
        link: "https://api.whatsapp.com/send?phone=5586995185757&text=Ol%C3%A1!%20Gostaria%20de%20contratar%20o%20Plano%20Mensal%20Simples.%0APode%20me%20ajudar%3F",
    },
	{
		id: 3,
        pricipal: true,
		title: 'Mensal Top',
		subtitle: '',
        description: 'Dedicação total e foco em resultados',
        value: "540",
        interval: "Mês",
        item1: "Total de 6 aulas (2h) no mês",
        item2: "Dúvidas por WhatsApp",
        item3: "Economia de 10%",
        link: "https://api.whatsapp.com/send?phone=5586995185757&text=Ol%C3%A1!%20Gostaria%20de%20contratar%20o%20Plano%20Mensal%20Top.%0APode%20me%20ajudar%3F",
    }
];